
language: c

env:
  - XCC=clang HOST= WINE= VALGRIND=
  - XCC=gcc HOST= WINE= VALGRIND=
  - XCC=i686-w64-mingw32-gcc HOST=i686-w64-mingw32 WINE=wine VALGRIND=
  - XCC=i586-mingw32msvc-gcc HOST=i586-mingw32msvc WINE=wine VALGRIND=
  - XCC=x86_64-w64-mingw32-gcc HOST=x86_64-w64-mingw32 WINE=wine64 VALGRIND=
  - XCC=clang HOST= WINE= VALGRIND=valgrind

before_install:
  - "sudo apt-get -qq update --force-yes > /dev/null"
  - "if [ x$WINE != x ]; then sudo apt-get install -qq wine > /dev/null; fi"
  - "if [ x$VALGRIND != x ]; then sudo apt-get install -qq valgrind > /dev/null; fi"
  - "if [ x$XCC = xclang ]; then sudo apt-get install -qq clang; fi"
  - "if [ x$XCC = xgcc ]; then sudo apt-get install -qq gcc; fi"
  - "if [ x$XCC = xi686-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-i686 binutils-mingw-w64-i686; fi"
  - "if [ x$XCC = xi586-mingw32msvc-gcc ]; then sudo apt-get install -qq mingw32; fi"
  - "if [ x$XCC = xx86_64-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64; fi"

before_script:
  - "CC=$XCC ./configure --host=$HOST"

script:
  - "make"
  - "sudo make install"
  - "$VALGRIND $WINE img2sixel images/snake.jpg > snake1.sixel"
  - "du -h snake1.sixel"
  - "$VALGRIND $WINE img2sixel -p16 images/snake.jpg > snake2.sixel"
  - "du -h snake2.sixel"
  - "$VALGRIND $WINE sixel2png -i snake1.sixel -o snake1.png"
  - "du -h snake1.png"
  - "$VALGRIND $WINE sixel2png < snake2.sixel > snake2.png"
  - "du -h snake2.png"
  - "$VALGRIND $WINE img2sixel snake1.png > snake3.sixel"
  - "du -h snake3.sixel"
  - "if [ x$VALGRIND != x ]; then valgrind --leak-check=yes --error-limit=no img2sixel images/snake.jpg -dfs | grep "ERROR SUMMARY: 0 errors" || exit 1; fi
  - "if [ x$VALGRIND != x ]; then valgrind --leak-check=yes --error-limit=no img2sixel images/snake.jpg -datkinson | grep "ERROR SUMMARY: 0 errors" || exit 1; fi
  - "if [ x$VALGRIND != x ]; then valgrind --leak-check=yes --error-limit=no img2sixel images/snake.jpg -jajuni | grep "ERROR SUMMARY: 0 errors" || exit 1; fi
  - "if [ x$VALGRIND != x ]; then valgrind --leak-check=yes --error-limit=no img2sixel images/snake.jpg -stucki | grep "ERROR SUMMARY: 0 errors" || exit 1; fi
  - "if [ x$VALGRIND != x ]; then valgrind --leak-check=yes --error-limit=no img2sixel images/snake.jpg -dburkes | grep "ERROR SUMMARY: 0 errors" || exit 1; fi
