
language: c

env:
  - XCC=clang HOST= WINE=
  - XCC=gcc HOST= WINE=
  - XCC=i686-w64-mingw32-gcc HOST=i686-w64-mingw32 WINE=wine
  - XCC=i586-mingw32msvc-gcc HOST=i586-mingw32msvc WINE=wine
  - XCC=x86_64-w64-mingw32-gcc HOST=x86_64-w64-mingw32 WINE=wine64
  - XCC=amd64-mingw32msvc-gcc HOST=amd64-mingw32msvc WINE=wine64

before_install:
    #  - "sudo apt-get -qq update --force-yes > /dev/null"
  - "if [ x$WINE != x ]; then sudo apt-get install -qq wine > /dev/null; fi"
  - "if [ x$XCC = xclang ]; then sudo apt-get install -qq clang; fi"
  - "if [ x$XCC = xgcc ]; then sudo apt-get install -qq gcc; fi"
  - "if [ x$XCC = xi686-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-i686 binutils-mingw-w64-i686; fi"
  - "if [ x$XCC = xi586-mingw32msvc-gcc ]; then sudo apt-get install -qq mingw32; fi"
  - "if [ x$XCC = xx86_64-w64-mingw32-gcc ]; then sudo apt-get install -qq gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64; fi"
  - "if [ x$XCC = xamd64-mingw32msvc-gcc ]; then sudo apt-get install -qq mingw32; fi"

before_script:
  - "uname -a"
  - "uname -r"
  - "CC=$XCC ./configure --host=$HOST"

script:
  - "make"
  - "$WINE converters/img2sixel images/snake.jpg > snake1.sixel"
  - "du -h snake1.sixel"
  - "$WINE converters/img2sixel -p16 images/snake.jpg > snake2.sixel"
  - "du -h snake2.sixel"
  - "$WINE converters/sixel2png -i snake1.sixel -o snake1.png"
  - "du -h snake1.png"
  - "$WINE converters/sixel2png < snake2.sixel > snake2.png"
  - "du -h snake2.png"
  - "$WINE converters/img2sixel snake1.png > snake3.sixel"
  - "du -h snake3.sixel"

