name: libsixel build
on: [push]
jobs:
  libsixel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libpng-dev libjpeg-dev libgd-dev libcurl4-openssl-dev libgdk-pixbuf2.0-dev libpython2-dev
      - name: ./configure
        run: ./configure --enable-python --enable-tests --with-gdk-pixbuf2 --with-gd --with-libcurl --with-jpeg --with-png
      - name: make
        run: make
      - name: make check
        run: make check
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libsixel_${{ matrix.platform }}
          path: |
            src/.libs/libsixel.so
            src/libsixel.la
            converters/img2sixel
            converters/sixel2png
