name: libsixel build
on: [push]
jobs:
  libsixel:
    runs-on: ubuntu-latest # 20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libpng-dev libjpeg-dev libgd-dev libcurl4-openssl-dev libgdk-pixbuf2.0-dev libpython2-dev
      - name: ./configure
        run: ./configure --enable-python --enable-tests --with-gdk-pixbuf2 --with-gd --with-libcurl --with-jpeg --with-png
      - name: make
        run: make
      - name: make check
        run: make check
      - name: Move artifacts
        run: mv src/.libs/libsixel.so .
        run: mv src/libsixel.la .
        run: mv converters/img2sixel .
        run: mv converters/sixel2png .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libsixel_linux
          path: |
            libsixel.so
            libsixel.la
            img2sixel
            sixel2png
